# Generated by Django 2.2.8 on 2019-12-08 04:42

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=30)),
                ('period', django.contrib.postgres.fields.ranges.DateTimeRangeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.Account')),
            ],
            options={
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionsSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Subscription Summary',
                'verbose_name_plural': 'Subscriptions Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('subscriptions.subscriptions',),
        ),
    ]
