# Generated by Django 2.2.8 on 2019-12-09 16:50

import apps.auth.enums
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.auth.enums.UserRole),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
