# Generated by Django 2.2.8 on 2020-01-21 02:05

import apps.auth.enums
from django.db import migrations
import django_enumfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0004_auto_20191220_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='source',
            field=django_enumfield.db.fields.EnumField(default=0, enum=apps.auth.enums.UserSource),
        ),
    ]
