# Generated by Django 2.2.8 on 2019-12-08 04:42

import apps.account.enums
import creditcards.models
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', creditcards.models.CardNumberField(max_length=25, null=True)),
                ('cvc', creditcards.models.SecurityCodeField(max_length=4, null=True)),
                ('expiry', creditcards.models.CardExpiryField(null=True)),
                ('brand', models.CharField(blank=True, max_length=10)),
                ('last4', models.CharField(blank=True, max_length=5)),
                ('customer_id', models.CharField(blank=True, max_length=70)),
                ('stripe_id', models.CharField(blank=True, max_length=50)),
                ('token', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CompanionInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('status', django_enumfield.db.fields.EnumField(default=0, enum=apps.account.enums.CompanionInviteStatus)),
                ('invite_code', models.CharField(max_length=50)),
                ('invited', models.DateTimeField(auto_now_add=True)),
                ('accessed', models.DateTimeField(blank=True, null=True)),
                ('signed_up', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DealWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', django.contrib.postgres.fields.jsonb.JSONField()),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('airlines', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FrequentFlyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('american_airlines', models.CharField(blank=True, max_length=30)),
                ('united_airlines', models.CharField(blank=True, max_length=30)),
                ('southwest_airlines', models.CharField(blank=True, max_length=30)),
                ('sun_country_airlines', models.CharField(blank=True, max_length=30)),
                ('frontier_airlines', models.CharField(blank=True, max_length=30)),
                ('delta_airlines', models.CharField(blank=True, max_length=30)),
                ('alaska_airlines', models.CharField(blank=True, max_length=30)),
                ('jetBlue', models.CharField(blank=True, max_length=30)),
                ('spirit_airlines', models.CharField(blank=True, max_length=30)),
                ('allegiant_air', models.CharField(blank=True, max_length=30)),
                ('hawaiian_airlines', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
