# Generated by Django 2.2.8 on 2020-01-22 00:37

import apps.account.enums
from django.db import migrations
import django_enumfield.db.fields

from django.conf import settings


def assign_kinds(apps_, schema_editor):
    DealWatchGroup = apps_.get_model("account", "DealWatchGroup")
    for o in DealWatchGroup.objects.all():
        if o.watches.exists():
            o.kind = apps.account.enums.DWGKind.private
            o.save()
        else:
            st, sv = o.source.split(":")
            dt, dv = o.destination.split(":")
            if not (st == "city" and dt == "city"):
                continue
            if sv in settings.DEALS_CITIES and dv in settings.DEALS_CITIES:
                o.kind = apps.account.enums.DWGKind.domestic
                o.save()
            elif sv in settings.DEALS_INTERNATIONAL and dv in settings.DEALS_INTERNATIONAL:
                o.kind = apps.account.enums.DWGKind.international
                o.save()
            else:
                print(f'Unknown DWG {o.source} -> {o.destination}')


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20191219_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealwatchgroup',
            name='kind',
            field=django_enumfield.db.fields.EnumField(default=-1, enum=apps.account.enums.DWGKind),
        ),
        migrations.RunPython(assign_kinds, migrations.RunPython.noop)
    ]
