# Generated by Django 2.2.8 on 2019-12-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20191209_1648'),
        ('booking', '0002_auto_20191208_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.DealWatchGroup'),
        ),
    ]
