# Generated by Django 2.2.8 on 2020-01-11 20:30

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_deal_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('trigger', models.CharField(max_length=50)),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
