# Generated by Django 2.2.10 on 2020-02-21 19:45

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_auto_20200118_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='country_from',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='country_to',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['country_from', 'country_to'], name='booking_dea_country_ba5e07_btree'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=django.contrib.postgres.indexes.GinIndex(fields=['airlines'], name='booking_dea_airline_4c22ab_gin'),
        ),
    ]
