apiVersion: apps/v1
kind: Deployment
metadata:
  name: wanderift-deployment
spec:
  selector:
    matchLabels:
      app: wanderift
  replicas: 1
  template:
    metadata:
      labels:
        app: wanderift
    spec:
      volumes:
        - name: gce-service-account-key
          secret:
            secretName: gce-service-account-key
      containers:
        - name: wanderift
          image: registry.gitlab.com/zburau/joinflyline:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: TWITTER_CONSUMER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_KEY

            - name: TWITTER_CONSUMER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_SECRET_KEY

            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN

            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: SENDINBLUE_API_KEY

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
        - name: worker
          command: ['inv', 'worker']
          image: registry.gitlab.com/zburau/joinflyline:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: TWITTER_CONSUMER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_KEY

            - name: TWITTER_CONSUMER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_SECRET_KEY

            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN

            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: SENDINBLUE_API_KEY

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
        - name: beat
          command: ['inv', 'beat']
          image: registry.gitlab.com/zburau/joinflyline:master
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: TWITTER_CONSUMER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_KEY

            - name: TWITTER_CONSUMER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_SECRET_KEY

            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN

            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: SENDINBLUE_API_KEY

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'

          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
      initContainers:
        - name: migrate
          image: registry.gitlab.com/zburau/joinflyline:master
          imagePullPolicy: Always
          command: ['python', 'manage.py', 'migrate']
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: TWITTER_CONSUMER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_KEY

            - name: TWITTER_CONSUMER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_SECRET_KEY

            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN

            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: SENDINBLUE_API_KEY

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
        - name: collectstatic
          image: registry.gitlab.com/zburau/joinflyline:master
          imagePullPolicy: Always
          command: ['inv', 'static']
          envFrom:
            - configMapRef:
                name: env-config
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: POSTGRES_PASSWORD

            - name: TWITTER_CONSUMER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_KEY

            - name: TWITTER_CONSUMER_API_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_CONSUMER_API_SECRET_KEY

            - name: TWITTER_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN

            - name: TWITTER_ACCESS_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: TWITTER_ACCESS_TOKEN_SECRET

            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: STRIPE_API_KEY

            - name: SENDINBLUE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: SENDINBLUE_API_KEY

            - name: FOR_GODS_SAKE_PLEASE_REDEPLOY
              value: 'THIS_STRING_IS_REPLACED_DURING_BUILD'
          volumeMounts:
            - name: gce-service-account-key
              readOnly: true
              mountPath: /etc/secrets
      imagePullSecrets:
        - name: gitlab-registry
