CITY_CODES = [
    ["Atlanta", "ATL"],
    ["Austin", "AUS"],
    ["Boston", "BOS"],
    ["Charlotte", "CLT"],
    ["Chicago", "CHI"],
    ["Dallas", "DFW"],
    ["Denver", "DEN"],
    ["Detroit", "DTT"],
    ["Las Vegas", "LAS"],
    ["Los Angeles", "LAX"],
    ["Miami", "MIA"],
    ["New York", "NYC"],
    ["Orlando", "ORL"],
    ["Philadelphia", "PHL"],
    ["Salt Lake City", "SLC"],
    ["San Francisco", "SFO"],
    ["Seattle", "SEA"],
]
